import type { AvailableMermasFilters } from './mermas/types';

export const qk = {
  health: ['health'] as const,
  capabilities: ['capabilities'] as const,
  orgProfile: ['org', 'profile'] as const,
  orgStats: ['org', 'stats'] as const,
  mermas: (f: AvailableMermasFilters = {}) => ['mermas', 'available', f] as const,
  mermasAll: ['mermas'] as const,
  merma: (id: string) => ['mermas', 'detail', id] as const,
  mermaNutrition: (id: string) => ['nutrition', 'merma', id] as const,
  applications: (status?: string) => ['applications', 'list', status ?? 'all'] as const,
  applicationsAll: ['applications'] as const,
  application: (id: string) => ['applications', 'detail', id] as const,
  assignments: (status?: string) => ['assignments', 'list', status ?? 'all'] as const,
  assignmentsAll: ['assignments'] as const,
  assignment: (id: string) => ['assignments', 'detail', id] as const,
  pickers: (assignmentId: string) => ['assignments', 'pickers', assignmentId] as const,
  eligibleContacts: (assignmentId: string) => ['assignments', 'eligible', assignmentId] as const,
  contacts: (orgId: string) => ['org', 'contacts', orgId] as const,
  authorizations: (orgId: string, contactId: string) =>
    ['org', 'authorizations', orgId, contactId] as const,
  notifications: ['notifications', 'list'] as const,
  notificationsAll: ['notifications'] as const,
  unreadCount: ['notifications', 'unread'] as const,
  nutritionGroups: ['nutrition', 'groups'] as const,
  nutritionSummary: (from: string, to: string) => ['nutrition', 'summary', from, to] as const,
  productSearch: (q: string) => ['nutrition', 'products', q] as const,
  families: ['families', 'list'] as const,
  familiesAll: ['families'] as const,
  family: (id: string) => ['families', 'detail', id] as const,
  demographics: ['families', 'demographics'] as const,
  familyTypes: ['families', 'types'] as const,
  requirements: (orgId: string) => ['docs', 'requirements', orgId] as const,
  documents: (orgId: string) => ['docs', 'documents', orgId] as const,
  socialData: (orgId: string) => ['docs', 'social', orgId] as const,
  commitments: (orgId: string, year: number) => ['programs', 'commitments', orgId, year] as const,
  programs: ['programs', 'list'] as const,
  trainings: (programId: string) => ['programs', 'trainings', programId] as const,
  sessions: ['programs', 'sessions'] as const,
};
